name: Dependency Check

on:
  workflow_dispatch:
  schedule:
  - cron: '0 5 * * *'

jobs:
  Dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        show-progress: false
        fetch-depth: 1
    - name: Dotnet Version
      run: dotnet --version
    - name: Check dependencies
      uses: mawosoft/dotnet-dependency-alert@v1
